---
title: "Vorlesung KI"
page-layout: article
---

# Willkommen

Dieses Skript bündelt die Inhalte der Vorlesung Machine Learning in Einheiten. 
Die Einheiten enthalten neben erklärendem Text Code, welcher beispielsweise in Jupyter Notebooks kopiert und ausgeführt werden kann.
Darüber hinaus gibt es zu jedem Kapitel passende Übungsaufgaben, sie selbstständig erarbeitet werden.

Das Skript wurde mit (Quarto)[https://quarto.org/docs/get-started/hello/jupyter.html] geschrieben und ist als lebendes Skript zu verstehen, welches laufend erweitert wird.


::: callout-tip
Mit dem Menü auf der Linken Seite kann man zwischen den einzelnen Einheiten hin- und herspringen.
Das zu der Einheit gehörende Untermenü ist auf der rechten Seite zu sehen, die Unterkapitel klappen dabei dymanmisch auf.
:::


## Einheiten
1. [Einführung](notebooks/01-einleitung.ipynb)  
2. [Das Perzeptron](notebooks/02-perzeptron.ipynb)  
3. [Überwachtes Lernen](notebooks/03-ueberwachtes_lernen.ipynb)  
4. [Zahlen erkennen](notebooks/04-zahlen_erkennen.ipynb)  
5. [CNN](notebooks/05-cnn.ipynb)  
5. [Nicht überwachtes Lernen](notebooks/06-nicht_ueberwachtes_lernen.ipynb) 
6. [Reinforced Learning](notebooks/07-reinforced_learning.ipynb)
7. [Zeitreihen](notebooks/08-zeitreihen.ipynb)
8. [Zusammenfassung](notebooks/09-zusammenfassung.ipynb)
